# Generated by Django 5.2.8 on 2026-01-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_roles', models.CharField(max_length=255)),
                ('confidence_scores', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField()),
                ('user_id', models.BigIntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'prediction_history',
                'managed': False,
            },
        ),
    ]
