# Generated by Django 5.2.8 on 2025-12-02 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('prediction_id', models.AutoField(primary_key=True, serialize=False)),
                ('predicted_roles', models.CharField(max_length=255)),
                ('confidence_scores', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
            options={
                'db_table': 'prediction_history',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('year_of_completion', models.IntegerField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('cert_id', models.AutoField(primary_key=True, serialize=False)),
                ('cert_name', models.CharField(max_length=100)),
                ('issuing_organization', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
            options={
                'db_table': 'certification',
            },
        ),
        migrations.CreateModel(
            name='AdminLogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to='accounts.users')),
                ('target_user', models.ForeignKey(db_column='target_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='target_logs', to='accounts.users')),
            ],
            options={
                'db_table': 'admin_logs',
            },
        ),
    ]
