# Generated by Django 5.2.8 on 2026-01-13 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_complete', models.BooleanField(default=False)),
                ('predictions', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_snapshot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_snapshot',
            },
        ),
    ]
